
# Documentation: http://docs.travis-ci.com/user/languages/julia/
codecov: true
coveralls: true
language: julia
os:
  - linux
  - windows
  - osx
julia:
  - 1.2
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
