name = "DefaultArrays"
uuid = "bb1859e0-6c46-48fc-af17-5b269a75ae2f"
authors = ["Francesco Alemanno <francescoalemanno710@gmail.com>"]
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
